INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME) VALUES ('JOHN', 'SMITH');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME) VALUES ('JANE', 'SMITH');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME) VALUES ('ROBERT', 'BROWN');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME) VALUES ('RUTH', 'BLACK');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME) VALUES ('RAVI', 'KUMAR');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME) VALUES ('RANI', 'GUPTA');

INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('ARNOLD', 'JUICEMAN');
INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('SYLVESTER', 'TALLON');
INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('ALICIA', 'STONE');
INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('TAYLOR', 'GLOW');
INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('BARDIEM', 'ZALLOW');
INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('PINEAPLE', 'CRUZ');