CREATE TABLE DOCTOR(
  EMPLOYEE_ID BIGSERIAL PRIMARY KEY,
  FIRST_NAME VARCHAR(16) NOT NULL,
  LAST_NAME VARCHAR(16) NOT NULL
);

CREATE TABLE PATIENT(
  PATIENT_ID BIGSERIAL PRIMARY KEY,
  FIRST_NAME VARCHAR(16) NOT NULL,
  LAST_NAME VARCHAR(16) NOT NULL
);